// Admin-only endpoints for the /admin dashboard.
//
//   GET /api/admin/ai-flows?window=7d|24h
//     Per-AI-flow usage from PostHog: models used, request count, error
//     rate, cost, fallback share, live prompt/config versions.
//
//   GET /admin-data/* (static assets, gated here before the ASSETS binding)
//     Currently just ai-prompts.json — the prompt-template snapshot
//     generated by web/scripts/extract-ai-prompts.mjs. It must never be
//     served unauthenticated: prompts are product IP and are deliberately
//     not public.
//
// Auth: the browser signs in with Google via Supabase Auth and sends the
// resulting access token as a Bearer header. We verify the token against
// GoTrue and allow exactly one account. There is no role system — this is a
// single-operator app.
//
// Env:
//   SUPABASE_URL               (var, already set)
//   SUPABASE_PUBLISHABLE_KEY   (var; public by design)
//   POSTHOG_PERSONAL_API_KEY   (secret; already set for /api/stats)
//   POSTHOG_PROJECT_ID         (optional; defaults to GainFrame)
//   POSTHOG_HOST               (optional)

export interface AdminEnv {
  SUPABASE_URL?: string;
  SUPABASE_PUBLISHABLE_KEY?: string;
  POSTHOG_PERSONAL_API_KEY?: string;
  POSTHOG_PROJECT_ID?: string;
  POSTHOG_HOST?: string;
}

export const ADMIN_EMAILS = ["michaelrode44@gmail.com"];

const JSON_HEADERS = {
  "Content-Type": "application/json",
  "Cache-Control": "no-store",
};

function deny(status: number, error: string): Response {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: JSON_HEADERS,
  });
}

/**
 * Resolves the Bearer token to a verified admin email, or null. Fails closed
 * on any missing config, GoTrue error, or non-allowlisted account.
 */
export async function verifyAdmin(
  request: Request,
  env: AdminEnv,
): Promise<boolean> {
  const auth = request.headers.get("Authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7).trim() : "";
  if (!token || !env.SUPABASE_URL || !env.SUPABASE_PUBLISHABLE_KEY) {
    return false;
  }
  try {
    const res = await fetch(`${env.SUPABASE_URL}/auth/v1/user`, {
      headers: {
        apikey: env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${token}`,
      },
    });
    if (!res.ok) return false;
    const user = (await res.json()) as { email?: string };
    const email = user.email?.toLowerCase() ?? "";
    return ADMIN_EMAILS.includes(email);
  } catch (err) {
    console.warn("admin auth check failed", err);
    return false;
  }
}

interface FlowModelRow {
  flow: string;
  model: string;
  provider: string;
  requests: number;
  errors: number;
  costUsd: number;
  fallbackRequests: number;
  lastSeen: string;
  promptVersion: string | null;
  configVersion: string | null;
}

// PostHog events carry two generations of flow naming: legacy display labels
// ("ClassifyAndScore", "Weekly Summary") from the pre-gateway fleet and
// canonical snake_case from the gateway. Mirror of LEGACY_LABEL_TO_FLOW in
// gain-frame supabase/functions/_shared/ai/flow.ts.
const LEGACY_LABEL_TO_FLOW: Record<string, string> = {
  ClassifyAndScore: "classify_score",
  Review: "review",
  "Deep Dive": "deep_dive",
  "Deep Dive Retry": "deep_dive_retry",
  "Deep Dive Preview": "deep_dive_preview",
  "Deep Dive Preview Retry": "deep_dive_preview_retry",
  "Deep Dive Compare": "deep_dive_compare",
  "Deep Dive Compare Retry": "deep_dive_compare_retry",
  "Check-In Read": "check_in_read",
  Caption: "caption",
  TargetAssessment: "target_assessment",
  ExerciseSuggestion: "exercise_suggestion",
  ReplacementExercise: "replacement_exercise",
  ProgressEvaluation: "progress_evaluation",
  "Correlation Prose": "correlation_prose",
  "Precision BF": "precision_bf",
  "Weekly Summary": "weekly_summary",
  "Pose Analysis": "pose_analysis",
  MemoryExtractor: "memory_extractor",
  "Nutrition Label Parse": "nutrition_label_parse",
  "Nutrition Recipe Import": "nutrition_recipe_import",
  "Starter Questions (general)": "starter_questions_general",
  "Starter Questions": "starter_questions",
  Comparison: "comparison",
  Prediction: "prediction",
  "Image Gen": "prediction_image",
  "Coach Hero Image Gen": "coach_hero_image",
  "Coach Hero Image (photo style)": "coach_hero_photo_style",
  "Goal Preview Image Gen": "goal_preview_image",
  "Onboarding Image Gen": "onboarding_image",
};

export function normalizeFlow(raw: string): string {
  if (LEGACY_LABEL_TO_FLOW[raw]) return LEGACY_LABEL_TO_FLOW[raw];
  return raw.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}

async function queryFlowUsage(
  env: AdminEnv,
  days: number,
): Promise<FlowModelRow[]> {
  const key = env.POSTHOG_PERSONAL_API_KEY;
  if (!key) throw new Error("POSTHOG_PERSONAL_API_KEY is not configured");
  const projectId = env.POSTHOG_PROJECT_ID || "357433";
  const host = env.POSTHOG_HOST || "https://us.posthog.com";

  const query = `
    SELECT
      coalesce(nullIf(properties.ai_flow, ''), nullIf(properties.gen_flow, '')) AS flow,
      toString(properties.$ai_model) AS model,
      toString(properties.$ai_provider) AS provider,
      count() AS requests,
      countIf(properties.$ai_is_error = true) AS errors,
      round(sum(properties.$ai_total_cost_usd), 4) AS cost_usd,
      countIf(properties.fallback_used = true) AS fallback_requests,
      toString(max(timestamp)) AS last_seen,
      argMax(toString(properties.prompt_version), timestamp) AS prompt_version,
      argMax(toString(properties.config_version), timestamp) AS config_version
    FROM events
    WHERE event = '$ai_generation'
      AND timestamp > now() - INTERVAL ${days} DAY
    GROUP BY flow, model, provider
    ORDER BY requests DESC
    LIMIT 500
  `;

  const res = await fetch(`${host}/api/projects/${projectId}/query/`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query: { kind: "HogQLQuery", query } }),
  });
  if (!res.ok) throw new Error(`posthog ${res.status}`);
  const data = (await res.json()) as {
    results?: Array<
      [
        string | null,
        string,
        string,
        number,
        number,
        number,
        number,
        string,
        string | null,
        string | null,
      ]
    >;
  };

  return (data.results ?? [])
    .filter((row) => row[0])
    .map((row) => ({
      flow: normalizeFlow(row[0] as string),
      model: row[1] || "unknown",
      provider: row[2] || "unknown",
      requests: row[3],
      errors: row[4],
      costUsd: row[5] ?? 0,
      fallbackRequests: row[6] ?? 0,
      lastSeen: row[7],
      promptVersion: row[8] === "null" ? null : row[8],
      configVersion: row[9] === "null" ? null : row[9],
    }));
}

export async function handleAdminAiFlows(
  request: Request,
  env: AdminEnv,
): Promise<Response> {
  if (!(await verifyAdmin(request, env))) {
    return deny(401, "Unauthorized.");
  }

  const window = new URL(request.url).searchParams.get("window");
  const days = window === "24h" ? 1 : 7;

  try {
    const rows = await queryFlowUsage(env, days);
    return new Response(
      JSON.stringify({ windowDays: days, generatedAt: new Date().toISOString(), rows }),
      { headers: JSON_HEADERS },
    );
  } catch (err) {
    console.error("admin ai-flows query failed", err);
    return deny(502, "Upstream query failed.");
  }
}
