// Admin-only endpoints for the /admin dashboard.
//
//   GET /api/admin/ai-flows?window=7d|24h
//     Per-AI-flow usage from PostHog: models used, request count, error
//     rate, cost, fallback share, live prompt/config versions.
//
//   GET /admin-data/* (static assets, gated here before the ASSETS binding)
//     Currently just ai-prompts.json — the prompt-template snapshot
//     generated by web/scripts/extract-ai-prompts.mjs. It must never be
//     served unauthenticated: prompts are product IP and are deliberately
//     not public.
//
// Auth: the browser signs in with Google via Supabase Auth and sends the
// resulting access token as a Bearer header. We verify the token against
// GoTrue and allow exactly one account. There is no role system — this is a
// single-operator app.
//
// Env:
//   SUPABASE_URL               (var, already set)
//   SUPABASE_PUBLISHABLE_KEY   (var; public by design)
//   POSTHOG_PERSONAL_API_KEY   (secret; already set for /api/stats)
//   POSTHOG_PROJECT_ID         (optional; defaults to GainFrame)
//   POSTHOG_HOST               (optional)

export interface AdminEnv {
  SUPABASE_URL?: string;
  SUPABASE_PUBLISHABLE_KEY?: string;
  POSTHOG_PERSONAL_API_KEY?: string;
  POSTHOG_PROJECT_ID?: string;
  POSTHOG_HOST?: string;
  REVENUECAT_API_KEY?: string;
  REVENUECAT_PROJECT_ID?: string;
}

export const ADMIN_EMAILS = ["michaelrode44@gmail.com"];

export const JSON_HEADERS = {
  "Content-Type": "application/json",
  "Cache-Control": "no-store",
};

export function deny(status: number, error: string): Response {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: JSON_HEADERS,
  });
}

export function ok(body: unknown): Response {
  return new Response(JSON.stringify(body), { headers: JSON_HEADERS });
}

/**
 * Runs one HogQL query and returns raw result rows. Throws on any non-200 so
 * callers surface a real error instead of rendering a silently empty panel.
 */
export async function hogql(
  env: AdminEnv,
  query: string,
): Promise<unknown[][]> {
  const key = env.POSTHOG_PERSONAL_API_KEY;
  if (!key) throw new Error("POSTHOG_PERSONAL_API_KEY is not configured");
  const projectId = env.POSTHOG_PROJECT_ID || "357433";
  const host = env.POSTHOG_HOST || "https://us.posthog.com";

  const res = await fetch(`${host}/api/projects/${projectId}/query/`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query: { kind: "HogQLQuery", query } }),
  });
  if (!res.ok) throw new Error(`posthog ${res.status}`);
  const data = (await res.json()) as { results?: unknown[][] };
  return data.results ?? [];
}

export const num = (v: unknown): number => (typeof v === "number" ? v : 0);
export const str = (v: unknown): string => (typeof v === "string" ? v : "");

/**
 * Resolves the Bearer token to a verified admin email, or null. Fails closed
 * on any missing config, GoTrue error, or non-allowlisted account.
 */
export async function verifyAdmin(
  request: Request,
  env: AdminEnv,
): Promise<boolean> {
  const auth = request.headers.get("Authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7).trim() : "";
  if (!token || !env.SUPABASE_URL || !env.SUPABASE_PUBLISHABLE_KEY) {
    return false;
  }
  try {
    const res = await fetch(`${env.SUPABASE_URL}/auth/v1/user`, {
      headers: {
        apikey: env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${token}`,
      },
    });
    if (!res.ok) return false;
    const user = (await res.json()) as { email?: string };
    const email = user.email?.toLowerCase() ?? "";
    return ADMIN_EMAILS.includes(email);
  } catch (err) {
    console.warn("admin auth check failed", err);
    return false;
  }
}

interface FlowModelRow {
  flow: string;
  model: string;
  provider: string;
  requests: number;
  errors: number;
  costUsd: number;
  fallbackRequests: number;
  lastSeen: string;
  promptVersion: string | null;
  configVersion: string | null;
}

// PostHog events carry two generations of flow naming: legacy display labels
// ("ClassifyAndScore", "Weekly Summary") from the pre-gateway fleet and
// canonical snake_case from the gateway. Mirror of LEGACY_LABEL_TO_FLOW in
// gain-frame supabase/functions/_shared/ai/flow.ts.
const LEGACY_LABEL_TO_FLOW: Record<string, string> = {
  ClassifyAndScore: "classify_score",
  Review: "review",
  "Deep Dive": "deep_dive",
  "Deep Dive Retry": "deep_dive_retry",
  "Deep Dive Preview": "deep_dive_preview",
  "Deep Dive Preview Retry": "deep_dive_preview_retry",
  "Deep Dive Compare": "deep_dive_compare",
  "Deep Dive Compare Retry": "deep_dive_compare_retry",
  "Check-In Read": "check_in_read",
  Caption: "caption",
  TargetAssessment: "target_assessment",
  ExerciseSuggestion: "exercise_suggestion",
  ReplacementExercise: "replacement_exercise",
  ProgressEvaluation: "progress_evaluation",
  "Correlation Prose": "correlation_prose",
  "Precision BF": "precision_bf",
  "Weekly Summary": "weekly_summary",
  "Pose Analysis": "pose_analysis",
  MemoryExtractor: "memory_extractor",
  "Nutrition Label Parse": "nutrition_label_parse",
  "Nutrition Recipe Import": "nutrition_recipe_import",
  "Starter Questions (general)": "starter_questions_general",
  "Starter Questions": "starter_questions",
  Comparison: "comparison",
  Prediction: "prediction",
  "Image Gen": "prediction_image",
  "Coach Hero Image Gen": "coach_hero_image",
  "Coach Hero Image (photo style)": "coach_hero_photo_style",
  "Goal Preview Image Gen": "goal_preview_image",
  "Onboarding Image Gen": "onboarding_image",
};

export function normalizeFlow(raw: string): string {
  if (LEGACY_LABEL_TO_FLOW[raw]) return LEGACY_LABEL_TO_FLOW[raw];
  return raw.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}

async function queryFlowUsage(
  env: AdminEnv,
  days: number,
): Promise<FlowModelRow[]> {
  const query = `
    SELECT
      coalesce(nullIf(properties.ai_flow, ''), nullIf(properties.gen_flow, '')) AS flow,
      toString(properties.$ai_model) AS model,
      toString(properties.$ai_provider) AS provider,
      count() AS requests,
      countIf(properties.$ai_is_error = true) AS errors,
      round(sum(properties.$ai_total_cost_usd), 4) AS cost_usd,
      countIf(properties.fallback_used = true) AS fallback_requests,
      toString(max(timestamp)) AS last_seen,
      argMax(toString(properties.prompt_version), timestamp) AS prompt_version,
      argMax(toString(properties.config_version), timestamp) AS config_version
    FROM events
    WHERE event = '$ai_generation'
      AND timestamp > now() - INTERVAL ${days} DAY
    GROUP BY flow, model, provider
    ORDER BY requests DESC
    LIMIT 500
  `;

  const rows = await hogql(env, query);
  return rows
    .filter((row) => row[0])
    .map((row) => ({
      flow: normalizeFlow(str(row[0])),
      model: str(row[1]) || "unknown",
      provider: str(row[2]) || "unknown",
      requests: num(row[3]),
      errors: num(row[4]),
      costUsd: num(row[5]),
      fallbackRequests: num(row[6]),
      lastSeen: str(row[7]),
      promptVersion: str(row[8]) === "null" ? null : str(row[8]) || null,
      configVersion: str(row[9]) === "null" ? null : str(row[9]) || null,
    }));
}

/** Daily AI spend, volume, and cache health — the margin trend line. */
async function queryCostTrend(env: AdminEnv) {
  const rows = await hogql(
    env,
    `SELECT toDate(timestamp) AS day,
            round(sum(properties.$ai_total_cost_usd), 2) AS cost_usd,
            count() AS requests,
            count(DISTINCT person_id) AS users,
            round(sum(toFloat(properties.cached_tokens)), 0) AS cached_tokens,
            round(sum(properties.$ai_input_tokens), 0) AS input_tokens
     FROM events
     WHERE event = '$ai_generation' AND timestamp > now() - INTERVAL 30 DAY
     GROUP BY day ORDER BY day DESC LIMIT 30`,
  );
  return rows.map((r) => ({
    day: str(r[0]),
    costUsd: num(r[1]),
    requests: num(r[2]),
    users: num(r[3]),
    cachedTokens: num(r[4]),
    inputTokens: num(r[5]),
  }));
}

/**
 * Heaviest AI consumers. person_id is PostHog's opaque UUID — no email or
 * name is fetched, this is only for spotting a runaway/whale account.
 */
async function queryTopSpenders(env: AdminEnv, days: number) {
  const rows = await hogql(
    env,
    `SELECT toString(person_id) AS person,
            round(sum(properties.$ai_total_cost_usd), 3) AS cost_usd,
            count() AS requests,
            count(DISTINCT coalesce(nullIf(properties.ai_flow, ''), nullIf(properties.gen_flow, ''))) AS flows
     FROM events
     WHERE event = '$ai_generation' AND timestamp > now() - INTERVAL ${days} DAY
     GROUP BY person ORDER BY cost_usd DESC LIMIT 10`,
  );
  return rows.map((r) => ({
    person: str(r[0]),
    costUsd: num(r[1]),
    requests: num(r[2]),
    flows: num(r[3]),
  }));
}

export async function handleAdminAiFlows(
  request: Request,
  env: AdminEnv,
): Promise<Response> {
  if (!(await verifyAdmin(request, env))) {
    return deny(401, "Unauthorized.");
  }

  const window = new URL(request.url).searchParams.get("window");
  const days =
    window === "24h" ? 1 : window === "30d" ? 30 : window === "14d" ? 14 : 7;

  try {
    const [rows, costTrend, topSpenders] = await Promise.all([
      queryFlowUsage(env, days),
      queryCostTrend(env),
      queryTopSpenders(env, days),
    ]);
    return ok({
      windowDays: days,
      generatedAt: new Date().toISOString(),
      rows,
      costTrend,
      topSpenders,
    });
  } catch (err) {
    console.error("admin ai-flows query failed", err);
    return deny(502, `Upstream query failed: ${err instanceof Error ? err.message : "unknown"}`);
  }
}
